### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Helloyunho** [Helloyunho/PurpleArchive#1]
- [ ] Make Google Drive API wrapper
- [ ] Make user-editable OS repo manager
- [ ] Automatically check the update(if possible)
- [ ] Download OS and automatically upload to Google Drive
- [ ] Hashsum check
- And maybe more...
